services:
  node:
    image: ghcr.io/yesbad/homelab-dash-oidc-traefik-ip-whitelist-all-the-buzzwords:master
    environment:
      - NODE_ENV=production
    volumes:
      - ./config.js:/app/config.js
      - ../traefik/dyn-whitelist.toml:/app/dyn-whitelist.toml
    ports:
      - "2500:2500"
